#!/usr/bin/env bash
set -euo pipefail

# Install dependencies
bun install

# Link .env from root project
ln -sf "$CONDUCTOR_ROOT_PATH/.env" .env

# Calculate API port (Wrangler runs on CONDUCTOR_PORT + 1)
API_PORT=$((CONDUCTOR_PORT + 1))

# Write .env.local with conductor-specific overrides
cat > .env.local <<EOF
# Auto-generated by Conductor — do not edit manually
VITE_API_PORT=${API_PORT}
EOF

echo "Setup complete. Vite on port ${CONDUCTOR_PORT}, Wrangler on port ${API_PORT}"
