#!/usr/bin/env bash
set -euo pipefail

# Install dependencies
bun install

# Link env files from the root project so secrets (API tokens, Cloudflare
# creds, etc.) stay in one place. .env is for Vite, .dev.vars is what
# `wrangler pages dev` reads to inject secrets into the function env, and
# .envrc is for direnv at the shell level.
ln -sf "$CONDUCTOR_ROOT_PATH/.env" .env
[ -f "$CONDUCTOR_ROOT_PATH/.dev.vars" ] && ln -sf "$CONDUCTOR_ROOT_PATH/.dev.vars" .dev.vars
[ -f "$CONDUCTOR_ROOT_PATH/.envrc" ] && ln -sf "$CONDUCTOR_ROOT_PATH/.envrc" .envrc

# Calculate API port (Wrangler runs on CONDUCTOR_PORT + 1)
API_PORT=$((CONDUCTOR_PORT + 1))

# Write .env.local with conductor-specific overrides
cat > .env.local <<EOF
# Auto-generated by Conductor — do not edit manually
VITE_API_PORT=${API_PORT}
EOF

echo "Setup complete. Vite on port ${CONDUCTOR_PORT}, Wrangler on port ${API_PORT}"
